name: build-and-push
on:
  push:
    branches: [ "main" ]
    paths:
      - "services/imo-api/**"
      - ".github/workflows/build.yaml"
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    # needed for GHCR
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push imo-api
        uses: docker/build-push-action@v6
        with:
          context: ./services/imo-api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/imo-api:sha-${{ github.sha }}
